services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: quua
            DB_USERNAME: admin
            DB_PASSWORD: quua_password
        networks:
            - app-network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - app-network

    migrator:
        build: .docker/php
        volumes:
            - ./:/var/www
        command:
            - php artisan migrate --force --seed
        depends_on:
            - php
            - db
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: quua
            DB_USERNAME: admin
            DB_PASSWORD: quua_password
        networks:
            - app-network

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: postgres:15-alpine
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "quua"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "quua_password"
        restart: always
        ports:
            - "5433:5432"
        networks:
            - app-network

volumes:
    db: {}

# Docker Networks
networks:
    app-network:
        driver: bridge
